config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :orders
  resources :products
  resources :categories
  resources :cart_line_items

end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user 
	belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
	validates_presence_of :title, :description
	validates_uniqueness_of :title
end

app/models/order.rb
class Order < ActiveRecord::Base

	before_validation  :assign_initial_values
	after_create :copy_cart_line_items_to_order_line_items
 	after_create :empty_user_cart_line_items
 	after_create :send_order_confirmation
	has_many :order_line_items
	belongs_to :user

	validates_presence_of :order_date, :order_number, :user_id
	

	def assign_initial_values
		self.order_date = Date.today
		self.order_number = "DCT-#{Random.rand(100..1000)}"
	end

	def copy_cart_line_items_to_order_line_items
		cart_line_items = CartLineItem.where('user_id = ?', self.user_id)
		order_total = 0
		cart_line_items.each do|cart_line_item|
			order_line_item = OrderLineItem.new
			order_line_item.order_id = self.id 
			order_line_item.product_id = cart_line_item.product_id
			order_line_item.price = cart_line_item.product.price
			order_line_item.quantity = cart_line_item.quantity
			order_total += order_line_item.price * order_line_item.quantity
			order_line_item.save 
		end	
		self.update_attributes(total: order_total)
	end


	def empty_user_cart_line_items 
		cart_line_items = CartLineItem.where('user_id = ?', self.user_id)
		cart_line_items.each do |cart_line_item|
			cart_line_item.destroy
		end
	end


	def send_order_confirmation
		Notification.order_confirmation(self).deliver!	
	end
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
	validates_presence_of :order_id, :product_id, :quantity, :price

	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base

	mount_uploader :avatar, AvatarUploader

	before_save  :generate_code 

	belongs_to :category
	has_many :cart_line_items
	has_many :order_line_items
	
	validates_presence_of :title, :description, :in_stock, :category_id, :price
	validates_numericality_of :price, :in_stock, :category_id
	validates_uniqueness_of :title

	private 

	def generate_code
		self.code = "DCT-#{SecureRandom.hex[0..4]}"
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :username, :mobile, :gender
  validates_uniqueness_of :username, :mobile
  validates_numericality_of :mobile
  validates_length_of :mobile, is: 10 

  has_many :cart_line_items
  has_many :orders


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :configure_permitted_parameters, if: :devise_controller?

  def check_is_admin
  	if current_user.is_admin  
  		return true
  	else
  		redirect_to root_path , notice: "you are not authorized"
  	end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :mobile, :gender])
  end
  protect_from_forgery with: :exception
end

app/controllers/cart_line_items_controller.rb
class CartLineItemsController < ApplicationController
	before_action :authenticate_user!

	def index
		@cart_items = current_user.cart_line_items
		@order = Order.new
	end

	def create
		product_id =  cart_line_item_params[:product_id]
		cart_line_item = current_user.cart_line_items.find_by(product_id: product_id)
		if cart_line_item
			cart_line_item.quantity += cart_line_item_params[:quantity].to_i
			cart_line_item.save
			redirect_to products_path, notice:"successfully added to cart"
		else
			@cart_item = CartLineItem.new(cart_line_item_params)
			if @cart_item.save
				redirect_to products_path, notice:"successfully added to cart"
			else
				redirect_to products_path, alert: "unable to add to cart"
			end		
		end
	end

	def destroy
		@cart_line_item = CartLineItem.find(params[:id])
		@cart_line_item.destroy
		redirect_to cart_line_items_path, notice: "The product has been deleted from cart" 
	end

	private 
	def cart_line_item_params
		params.require(:cart_line_item).permit(:product_id, :user_id, :quantity)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
   before_action :check_is_admin, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where("category_id = ?", params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice:"Category successfully created$$"
    else
      render action: 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to categories_path, notice:"Category updated successfully**"
    else
      render action: 'edit'
    end

  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice:"Category deleted successfully !!!!"
  end

  private
  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	before_action :authenticate_user!
	
	def index
		@orders =  current_user.orders		
	end

	def create
		@order = Order.new
		@order.user_id = current_user.id
		if @order.save
			redirect_to orders_path notice: "your order has been placed"
    end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:index,:show]
  before_action :check_is_admin, except: [:index, :show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartLineItem.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id), notice:"Product successfully created$$"
    else
      render action: "new"
    end

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path, notice: "Product updated successfully**"
    else
      render action: "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Product deleted successfully!!!"
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :description, :cod_eligible, :in_stock, :category_id, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_line_items_helper.rb
module CartLineItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cart_line_items/index.html.erb
<h1> Cart Items - <%= @cart_items.length %></h1>


<% if @cart_items.empty? %>
	<b> No products in your cart. Shop <%= link_to "here", products_path %> </b>
<%else%>
<%total_price = 0%>
<table border= "1">
	<thead>
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>Quantity</th>
		<th>Actual price</th>
		<th>Total Price</th>
		<th colspan="2">Action</th>
	</tr>		
	</thead>
	<tbody>
		<% @cart_items.each do |cart_item| %>
			<tr>
				<td><%= cart_item.id%></td>
				<%product = Product.find cart_item.product_id%>
				<td><%= product.title %> </td> 
				<td><%= cart_item.quantity %></td>
				<td><%= product.price%></td> 
				<%price = cart_item.quantity * product.price%>
				<td><%= price%></td>
				<% total_price += price%>
				<td> <button type="button">+</button> <%#= cart.quantity%> <button type="button">-</button>
        <%= link_to "remove",cart_line_item_path(cart_item.id), method: :delete, data: {confirm: "Are you sure want to remove product from cart??? "} %>
				</td>
			</tr>
		<%end%>				
	</tbody>
</table>

<h3>Total : <%= total_price%></h3>

<%= form_for @order do |f| %>
	<%= f.submit "Checkout" %>
<%end%>

<br/><br/>
<%= link_to "Continue Shopping", products_path %>
<% end %>

app/views/categories/_form.html.erb
<%= form_for @category do |form| %>
  Title: <%= form.text_field :title %> <br/><br/>
  Description: <%= form.text_area :description %> <br/><br/>
  <%= form.submit "Submit"  %><br/><br/>

<%end%>

app/views/categories/edit.html.erb
<h1> Edit category </h1>
<%= render 'form' %>

<%= link_to "Back", :back %>

app/views/categories/index.html.erb
<h1>Listing Categories - <%= @categories.length %></h1>
<% if user_signed_in? && current_user.is_admin %>
  <%= link_to "Add Category", new_category_path %>
<%end%>
<br/><br/>

<table border = 1>
  <thead>
    <tr>
      <th>Title</th>
    </tr>    
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.title.capitalize, category_path(category.id) %></td>
      </tr>
    <%end%>
  </tbody>
</table>

<br/><br/>
<%= link_to "Back", :back %>

app/views/categories/new.html.erb
<h1>Add new category </h1>
<%= render 'form' %>

<%= link_to "Back", :back %>

app/views/categories/show.html.erb
<h2><%= @category.title.capitalize %></h2>
<b>Description:</b> <%= @category.description.capitalize %><br/><br/>

<% if user_signed_in? && current_user.is_admin %>
	<%= link_to "Edit", edit_category_path(@category.id) %>
	<%= link_to "Delete", category_path(@category.id), method: :delete, data: {confirm: "are you sure??"} %>
<%end%>
<br/><br/>

<% if @products.length > 0 %>
  <%@products.each do |product|%>
    <%= link_to product.title.capitalize, product_path(product.id) %>
  <%end%>
<% else%>
  <h3> No products found!!!</h3>
<%end%>

<br/><br/>
<%= link_to "Back", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcommerceRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1> Welcome to Ecommerce </h1>
<% if user_signed_in? %>
  Welcome <%=current_user.username%> <%= link_to "Account settings", edit_user_registration_path %> 
  <%= link_to "Your Cart (#{current_user.cart_line_items.pluck(:quantity).inject(:+)})", cart_line_items_path %>

  <%= link_to "Your Orders", orders_path %>
	<%= link_to "Products", products_path%>
	<%= link_to "Categories", categories_path%>
	<%= link_to "Logout", destroy_user_session_path, method: :delete, data: {confirm: "logging out??"} %>
	<% else %>
		<%= link_to "Login", new_user_session_path %> | <%= link_to "Register", new_user_registration_path%>
	<%end%>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>
  

app/views/notification/order_confirmation.html.erb
<p> Hello <%= @order.user.username %>, <br/> 
    Your order has been confirmed
 </p>
 <h3> Your order Details </h3>
 <%= @order.order_date %> - <%= @order.order_number %> - <%= @order.total %>
<ol>
	<% @order.order_line_items.each do|order_line_item|%>
	<li>
		<%= order_line_item.product.title %> |
		<%= order_line_item.price %> |
		<%= order_line_item.quantity %> |
		<%= order_line_item.price * order_line_item.quantity %>		
	</li>
	<% end %>
</ol>

<p> Thank you for shopping with us... keep shopping</p>

app/views/notification/order_confirmation.text.erb
Notification#order_confirmation

<%= @greeting %>, find me in app/views/notification/order_confirmation.text.erb

app/views/orders/index.html.erb
<h2>Your Orders</h2>

<% if @orders.empty? %>
	<p> You have not places any orders yet...</p>
<%else%>
	<ul>
	<% @orders.each do |order| %>
		<li> <%= order.order_date %> - <%= order.order_number %> - <%= order.total %></li>
		<ol>
			<% order.order_line_items.each do|order_line_item|%>
				<li> <%= order_line_item.product.title %> - <%= order_line_item.price%> - <%= order_line_item.quantity%> <%= order_line_item.price * order_line_item.quantity%> </li>
			<%end%>
		</ol>
	<% end %>
	</ul>
	<% end %>

app/views/products/_form.html.erb
<%= form_for @product do |form| %>

  <%= form.label :category %> 
  <%= collection_select(:product, :category_id, Category.all, :id, :title, {:prompt => true, :multiple=>true })%><br/><br/>
	<%= form.label :title %>
	<%= form.text_field :title %><br/><br/>

	<%= form.label :price %>
	<%= form.number_field :price %><br/><br/>

	<%= form.label :description %> 
	<%= form.text_area :description %><br/><br/>

	<%= form.label :"In Stock" %> 
	<%= form.number_field :in_stock %><br/><br/>

	<%= form.label :"Cod Eligible "%> 
	<%= form.label :radio, "Yes"%>
  <%= form.radio_button(:cod_eligible, "true")%> 

  <%= form.label :radio, "No"%>
  <%= form.radio_button(:cod_eligible, "false")%><br/><br/>

  <%= form.label :avatar %>
  <%= form.file_field :avatar %>

  <br/><br/>
  <%= form.submit "Submit" %> 
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>

<%= link_to "Back", :back %>

app/views/products/index.html.erb
<h1>Listing Products - <%= @products.length %></h1> 

<% if user_signed_in? && current_user.is_admin %>
<%= link_to "Add New Product", new_product_path %><br/><br/>
<% end %>

<table border = 1>
	<thead>
		<tr>
			<th> Id</th>
			<th> Title </th>
			<th> Price </th>
			<th> Description </th>
			<th> Cod Eligible </th>
			<th> In Stock </th>
			<th> Category Id </th>
		</tr>		
	</thead>
	<tbody>
		<% @products.each do |product| %>
			<tr>
				<td> <%= product.id %> </td>
				<td> <%= link_to product.title.capitalize, product_path(product.id) %> </td>
				<td> <%= product.price %> </td>
				<td> <%= product.description.capitalize %> </td>
				<td> <%= product.cod_eligible %> </td>
				<td> <%= product.in_stock %> </td>
				<td> <%= product.category_id %> </td>
			</tr>
		<% end %>	
	</tbody>
</table>

<br/><br/> 



<%= link_to "Back", :back %>

app/views/products/new.html.erb
<h1>Add new product </h1>
<%= render 'form' %>

<%= link_to "Back", :back %>

app/views/products/show.html.erb
<h2> <%= @product.title.capitalize %> - <%= @product.code %> </h2>
<br/><br/>
<% if user_signed_in? && current_user.is_admin %>
<%= link_to "Edit", edit_product_path(@product.id) %> | <%= link_to "Delete", product_path(@product.id), method: :delete, data: {confirm: "are you sure??"}%> <br/><br/>
<% end %>
<%= image_tag(@product.avatar.url, style: 'height:100px;width:auto;') if @product.avatar %><br/><br/>
<b>Title:</b> <%= @product.title.capitalize %><br/><br/>
<b>Price:</b> <%= @product.price %><br/><br/>
<b>Description:</b> <%= @product.description.capitalize %><br/><br/>
<b>In Stock:</b> <%= @product.in_stock %><br/><br/>
<b>Cod Eligible:</b> <%= @product.cod_eligible %><br/><br/>
<b>Category:</b> <%= @product.category_id %> <br/><br/>

<h3> Add to cart </h3>

<%= form_for @cart_item do |form| %>
	<%= form.hidden_field :product_id, value: @product.id%>
	<%= form.hidden_field :user_id,  value: current_user.id %>
	<%= form.label :quantity %>
	<%= form.number_field :quantity %>
	<%= form.submit "Add to cart" %>
<%end%>

<%= link_to "Back", :back %>